kind:Deployment
apiVersion:apps/v1
metadata:
  name:java-app
  namespace:prod
spec:
  replicas:1
  selector:
    matchlabels:
      app:java-app
  template:
    metadata:
      labels:
        app:java-app
    spec:
      containers:
      - name:java-app
      image:sumithsraikar:Kubernetes-Deployment-Image
    
      ports:
      -containerPort: 80
    
