apiVersion: v1
kind: Service
metadata:
  name: java-app
  namespace: prod
spec:
  selector:
    app: java-app
  type: NodePort
  ports:
    - port: 80        
      targetPort: 80  
      nodePort: 30001
      protocol: TCP
