kind: deployment
apiVersion: apps/v1
metadata:
  name:
    app: java-app
    namespace: dev
spec:
  replicas: 2
  selector:  
    matchlables:
      app: java-app
  template:
    metadata:
      lables:
        app: java-app
    spec:
      container:
      -name: Kubernetes-Deployment-Image
       image: <docker-image>
       
      ports:
      -containerPort: 80
      
  
